### ISSUE TITLE
Question for Dataset

### ISSUE THREAD

**Issue by FyyStudy** [rlgnswk/Motion-Infilling-pytorch-version-implementation#1]
First of all thank you for making the code public. Than, can you share the dataset organisation or  catalogue? Thank you very much!

**Comment by rlgnswk** [comment]
Thank you for your comment.
Do you find the origin dataset?
There are links in README.
Please see the section: Data

'''
Data
Get data from Holden et al
Pre-pocessing by using code from Kaufmann et al
'''

If there is something misunderstanding, please let me know

**Comment by FyyStudy** [comment]
Thanks for your response. Yes, I have download the dataset as following. I don't how to use it by your dataloader or organize the data to use.  Perhaps I could ask for a copy of your data?

 The data structure is 
--data
-------external
----------------edin_kinect
----------------edin_locomotion
----------------edin_punching
----------------edin_terrain
-------processd
----------------cmu
----------------edin_XX
----------------edin_XX

**Comment by rlgnswk** [comment]
Unfortunately, I do not have that dataset now. Sorry for that.
As my memory, there is nothing to modify without  following preprocessing.
Have you also done following preprocessing step?

+
Did you check under the 112 line in data_load.py?
There is some test operation. I hope it help you.
